[project]
name = "openai_chat_kernel"
version = "0.1.0"
description = "OpenAI ChatGPT Jupyter Kernel"
readme = "README.md"
authors = [
    { name = "KASE Hiroyuki", email = "kase@sapphire-eng.jp" },
]
dependencies = [
    "ipykernel",
    "jupyter_client",
    "openai",
]


